name: malina
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  provider: ^6.1.2  
  shared_preferences: ^2.2.2
  mobile_scanner: ^5.1.1 
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.2

#Navigation
  auto_route: ^10.2.0
  freezed_annotation: ^3.1.0
  json_serializable: ^6.7.1
  auto_route_generator: ^10.2.5
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_gen: ^5.4.0 
  json_annotation: ^4.9.0
  freezed: ^3.2.3
  flutter_svg: ^2.0.10+1
  integration_test:
    sdk: flutter
  mockito: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
    - assets/icons/
    - assets/icons/lenta.svg
    - assets/icons/like.svg
    - assets/icons/menu.svg
    - assets/icons/user.svg
    - assets/icons/bag.svg

flutter_intl:
  enabled: true
  class_name: Localized
  main_locale: ru
  arb_dir: lib/src/gen/localization/l10n
  output_dir: lib/src/gen/localization
  use_deffered_loading: false